import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5173');
await expect(page.locator('.article-row').first()).toBeVisible();
await expect(page.getByRole('button',{name:'Gom theo Story'})).toHaveAttribute('aria-pressed','true');
await page.screenshot({path:'qa/story-desktop.png'});
await page.getByRole('button',{name:/Xem Story/}).first().click();
await expect(page.getByRole('dialog').locator('.story-member').first()).toBeVisible();
console.log('Story dialog violations',(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>v.id));
await page.screenshot({path:'qa/story-dialog.png'});
await page.getByRole('button',{name:'Hỏi AI về Story này'}).click();
await expect(page.locator('.chat-composer')).toContainText('Story đã chọn');
await page.setViewportSize({width:390,height:844});
await page.getByRole('link',{name:'Dòng thông tin',exact:true}).click();
await expect(page.locator('.article-row').first()).toBeVisible();
await page.getByRole('button',{name:/Xem Story/}).first().scrollIntoViewIfNeeded();
await page.screenshot({path:'qa/story-mobile.png'});
console.log('Mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
console.log('Runtime errors',errors);
await browser.close();
